version: '2'

services:
    web:
      build:
        context: ./
        dockerfile: web.docker
      ports:
        - "80:8000"
      links:
        - redis
      environment:
        - "REDIS_PORT=6379"
        - "REDIS_HOST=redis"
    redis:
      image: redis
      ports:
          - "6379:6379"